spring:
  application:
      name: feign
#  eureka:
#    client:
#      service-url:
#        defaultZone: http://localhost:8761/eureka/
#    instance:
#      prefer-ip-address: true
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&useSSL=false&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #kafka配置
#  kafka:
#    producer:
#      bootstrap-servers: 127.0.0.1:9092 # 会覆盖 spring.kafka.bootstrap-servers 配置
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer # 序列化key的类
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # 反序列化value的类
#    consumer:
#      bootstrap-servers: 127.0.0.1:9092 # 会覆盖 spring.kafka.bootstrap-servers 配置
#      group-id: kafka-test # 消费者所属消息组
#
#    bootstrap-servers: 127.0.0.1:9092
#    #redis配置
#  redis:
#    # Redis服务器地址
#    host: localhost
#    #Redis服务器连接端口
#    port: 6379
#    #password:
#    # Redis数据库索引（默认为0）
#    database: 1
#    # 连接超时时间（毫秒）
#    client-type : jedis
#    lettuce:
#      pool:
#        #连接池最大连接数（使用负值表示没有限制）
#        max-active: 100
#        # 连接池中的最小空闲连接
#        max-idle: 10
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: 100000

#mybatis-plus配置
mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath:mapper/**/*.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: com.hbw.*.mapper #切记路径是映射类路径
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      #逻辑删除
#      #删除前
#      logic-not-delete-value: ${db-config-not-delete}
#      #删除后
#      logic-delete-value: ${db-config-delete}
#配置控制台打印日志Debug
logging:
  level:
    com.jd.mapper: debug

# xxl-job配置
#xxl:
#  job:
#    admin:
#      # 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
#      addresses: http://localhost:8081/xxl-job-admin
#    executor:
#      # 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
#      address:
#      # 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
#      appname: hbw-app
#      # 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
#      ip:
#      # 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
#      port: 0
#      # 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
#      logpath: /data/xxl-job-log/jobhandler
#      # 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
#      logretentiondays: 15
#    # 执行器通讯TOKEN [选填]：非空时启用；
#    accessToken: default_token
server:
#  port: ${config.port}
  port: 1100

  # apollo配置
#app:
#  id: EpidemicPreventionAndControlSrv3
#apollo:
#  meta: http://192.168.186.1:8060
#  bootstrap:
#    enabled: true
#    eagerLoad:
#      enabled: true
#  autoUpdateInjectedSpringProperties: false

#feign:
#  hystrix:
#    enabled: true